### ISSUE TITLE
How to create web version of audio chatbot using polly

### ISSUE THREAD

**Issue by NeetaA** [App-vNext/Polly-Samples#12]
How to create web version of audio chatbot using polly

**Comment by reisenberger** [comment]
@neeta  This kind of very broad question is probably better discussed on our more interactive [public slack](www.pollytalk.org).  I've created a channel there, [PollyWithBots](https://pollytalk.slack.com/messages/C73MA9EMQ/), where some members of the group who've been involved with bots ( @ankitbko and others ) can possibly help.

Thanks.
