### ISSUE TITLE
Finalize (OnSuccess Action) the  WaitAndRetryAsync with a WrapAsync Policy

### ISSUE THREAD

**Issue by BartHuls** [App-vNext/Polly-Samples#20]
I have a FallbackAsync Policy combined with a WaitAndRetryAsync Policy.
Both Policies are wrapped together with WrapAsync.
FallbackPolicy.WrapAsync(RetryPolicy). This works.

Is have a need to add some Finalizer eq. When the WaitAndRetryAsync succeeds  like the fallbackAction but in the  WaitAndRetryAsync

**Comment by reisenberger** [comment]
Duplicate of https://github.com/App-vNext/Polly/issues/663
