### ISSUE TITLE
Discussion about getting rid of the sync demos

### ISSUE THREAD

**Issue by peter-csala** [App-vNext/Polly-Samples#64]
I'm proposing to get rid of the sync demos. Here is my rationale:
- Prior V8 you have to define separate policies for sync and async methods
- Since V8 you have a unified strategy which can be executed both in sync and in async way
- After the V8 migration the sync demos look like code-duplicates rather than great additions

Is there any objection to delete the sync demos?

**Comment by peter-csala** [comment]
@martincostello , @joelhulen

**Comment by martincostello** [comment]
I vote 🔥🗑️
